name: prolang
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase: ^7.3.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  cloud_functions: ^0.5.0
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.5
  google_sign_in: ^4.4.6
  provider: ^4.1.3
  flutter_auth_buttons: ^0.8.0
  flutter_platform_widgets: ^0.50.0
  easy_localization: ^2.3.2
  auto_size_text: ^2.1.0
  responsive_grid: ^1.1.1
  json_annotation: ^3.0.1
  responsive_builder: ^0.2.0+2
  tuple: ^1.0.3
  intro_slider: ^2.3.1
  flutter_icons: ^1.1.0
  collection: ^1.14.12
  flutter_sticky_header: ^0.4.2
  sliver_fab: ^1.0.0
  expandable: ^4.1.4
  card_settings:
    git:
      url: git://github.com/CoolONEOfficial/card_settings.git
  freezed_annotation: ^0.11.0
  chewie: ^0.9.10
  chewie_audio: ^1.0.0+1
  video_player: ^0.10.11+1
  auto_orientation: ^1.0.6
  file_picker_cross: ^2.0.0
  paginate_firestore: ^0.1.0
  full_screen_image: ^1.0.2
  cached_network_image: ^2.2.0+1
  step_progress_indicator: ^0.2.3+6
  tinycolor: ^1.0.2
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.4.10
  onesignal_flutter: ^2.5.0
  path_provider: ^1.6.9
  timer_builder: ^1.3.0
  audioplayers: ^0.15.1
  record_mp3: ^1.0.1
  permission_handler: ^5.0.0+hotfix.8
  emojis: ^0.8.1
  image: ^2.1.12
  crop: ^0.3.1+1
  email_validator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  freezed: ^0.11.0
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  native_pdf_view: ^3.6.2

flutter_native_splash:
  image: "assets/images/logo.png"
  color: 7E57C2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/logo_ios.jpg"
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "#7E57C2"
  adaptive_icon_foreground: "assets/images/logo_android.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TTNorms
      fonts:
        - asset: assets/fonts/TTNorms-Bold.ttf
          weight: 700
        - asset: assets/fonts/TTNorms-Regular.ttf
          weight: 500
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
